### ISSUE TITLE
Styling the Notes Application - Mark edited line

### ISSUE THREAD

**Issue by Ucodia** [survivejs/react#404]
In the "Styling Notes" section, one line is not marked as inserted (not in bold), namely this one:

```
className="editable"
```

Not a big deal but easy to miss out when writing the code along the tutorial.

Thank you very much for making this great tutorial.

**Comment by bebraw** [comment]
Thanks a lot!

Btw, what would you think of porting the tutorial to **CSS Modules**? That's one reason why styling is a separate chapter like this now. Easier to port over. I'm a little torn over that atm.

**Comment by Ucodia** [comment]
I have not reached the CSS Module part yet and therefore I don't know what it consists of yet so I cannot really tell what is ideal. I'll let you know after I went through it.

**Comment by bebraw** [comment]
Yeah. It's mentioned in the styling chapter. Here's the [spec](https://github.com/css-modules/css-modules) if you want to have a look. Basically we could do styling per component (local scope by default). But we can get back to that later. 👍

**Comment by Ucodia** [comment]
I had a look at CSS Modules and I can see how you would want to use these when designing reusable components. Now this chapter of the tutorial in its current state is pretty simple and straightforward. I don't know how steep it would be to introduce this new paradigm but I guess that is an important thing to consider to decide whether you want to port it or not.

I found that the whole tutorial was really "production ready" globally so having a dedicated chapter to CSS Modules would seem like a great addition. You could simply make it an optional chapter as a first approach and later decide to replace the initial one if that works out great.

**Comment by bebraw** [comment]
> I had a look at CSS Modules and I can see how you would want to use these when designing reusable components. Now this chapter of the tutorial in its current state is pretty simple and straightforward. I don't know how steep it would be to introduce this new paradigm but I guess that is an important thing to consider to decide whether you want to port it or not.

Yeah, discussing the idea early on would add more complexity. There's enough to learn as is. 👍 

> I found that the whole tutorial was really "production ready" globally so having a dedicated chapter to CSS Modules would seem like a great addition. You could simply make it an optional chapter as a first approach and later decide to replace the initial one if that works out great.

I set up an issue (#409) for tracking this. A chapter could be a starting point, yeah.
