### ISSUE TITLE
Incorrect path for images

### ISSUE THREAD

**Issue by ilbonte** [survivejs/react#410]
The path for the images is wrong: For example here  https://github.com/survivejs/react/blob/dev/manuscript/getting_started/01_introduction_to_react.md the first image link is https://github.com/survivejs/react/blob/dev/manuscript/getting_started/images/react_header.png
but I think that it should be https://github.com/survivejs/react/blob/dev/manuscript/images/react_header.png

**Comment by bebraw** [comment]
Hi,

The GitHub urls are not meant to work. Both Leanpub and the site look for the images from the root in a very specific way.

I don't consider GitHub rendering a priority given we cannot get special syntax like `T>` or `leanpub-start-insert` to work there.

Thanks for the report, though!

**Comment by ilbonte** [comment]
Oh, sorry... didn't know that!

**Comment by bebraw** [comment]
It's cool. 👍 

It would be nice to get a `dev` build of the book running somewhere somehow.
